# Generated by Django 5.2.3 on 2025-07-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_book_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='authors/')),
                ('bio', models.TextField(blank=True)),
                ('featured_month', models.DateField()),
                ('representative_work', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='review',
            name='cover_image',
        ),
    ]
