# Generated by Django 5.2.3 on 2025-07-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('M', '남성'), ('F', '여성'), ('O', '기타')], max_length=10),
        ),
    ]
