# Generated by Django 5.2.3 on 2025-07-09 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_gender'),
        ('accounts', '0002_customuser_profile_image'),
    ]

    operations = [
    ]
